-- PostgreSQL Database Migration Script for Farm Management System
-- Initial schema setup

-- Drop tables if they exist (for fresh setup)
DROP TABLE IF EXISTS EQUIPMENT_REQUESTS CASCADE;
DROP TABLE IF EXISTS DIAGNOSTICS CASCADE;
DROP TABLE IF EXISTS ATTENDANCE CASCADE;
DROP TABLE IF EXISTS TASKS CASCADE;
DROP TABLE IF EXISTS FARM_ASSIGNMENTS CASCADE;
DROP TABLE IF EXISTS WEATHER CASCADE;
DROP TABLE IF EXISTS FARM_DETAILS CASCADE;
DROP TABLE IF EXISTS FARMS CASCADE;
DROP TABLE IF EXISTS USER_ROLES CASCADE;
DROP TABLE IF EXISTS PROFILES CASCADE;
DROP TABLE IF EXISTS USERS CASCADE;

-- Create USERS table
CREATE TABLE USERS (
    ID VARCHAR(36) PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    ROLE VARCHAR(50),
    NAME VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT NOW() NOT NULL
);

CREATE INDEX IDX_USERS_EMAIL ON USERS(EMAIL);

-- Create PROFILES table
CREATE TABLE PROFILES (
    ID VARCHAR(36) PRIMARY KEY,
    FULL_NAME VARCHAR(255),
    PHONE VARCHAR(20),
    AVATAR_URL VARCHAR(500),
    CREATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    FOREIGN KEY (ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- Create USER_ROLES table
CREATE TABLE USER_ROLES (
    ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(36) NOT NULL,
    ROLE VARCHAR(50) NOT NULL,
    ASSIGNED_DATE TIMESTAMP DEFAULT NOW() NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

CREATE INDEX IDX_USER_ROLES_USER_ID ON USER_ROLES(USER_ID);
CREATE INDEX IDX_USER_ROLES_ROLE ON USER_ROLES(ROLE);

-- Create FARMS table
CREATE TABLE FARMS (
    ID VARCHAR(36) PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    LOCATION VARCHAR(500),
    VILLAGE VARCHAR(255),
    PINCODE VARCHAR(10),
    AREA_SQM NUMERIC(12, 2),
    TOTAL_LAND NUMERIC(10, 2),
    CROP VARCHAR(255),
    GROWTH_STAGE VARCHAR(50),
    CROP_HEALTH_SCORE INTEGER,
    EXPECTED_REVENUE NUMERIC(15, 2),
    PROFIT_SHARE NUMERIC(5, 2),
    CONTRACT_SUMMARY VARCHAR(1000),
    OWNER_ID VARCHAR(36),
    CREATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    CREATED_BY VARCHAR(36),
    FOREIGN KEY (OWNER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID)
);

CREATE INDEX IDX_FARMS_OWNER_ID ON FARMS(OWNER_ID);
CREATE INDEX IDX_FARMS_VILLAGE ON FARMS(VILLAGE);

-- Create FARM_DETAILS table (for soil data)
CREATE TABLE FARM_DETAILS (
    ID VARCHAR(36) PRIMARY KEY,
    FARM_ID VARCHAR(36) NOT NULL,
    SOIL_PH NUMERIC(4, 2),
    SOIL_NITROGEN NUMERIC(10, 2),
    SOIL_PHOSPHORUS NUMERIC(10, 2),
    SOIL_POTASSIUM NUMERIC(10, 2),
    SOIL_ORGANIC_CARBON NUMERIC(10, 2),
    SOIL_MOISTURE NUMERIC(5, 2),
    CREATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    FOREIGN KEY (FARM_ID) REFERENCES FARMS(ID) ON DELETE CASCADE
);

CREATE INDEX IDX_FARM_DETAILS_FARM_ID ON FARM_DETAILS(FARM_ID);

-- Create FARM_ASSIGNMENTS table
CREATE TABLE FARM_ASSIGNMENTS (
    ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(36) NOT NULL,
    FARM_ID VARCHAR(36) NOT NULL,
    ROLE VARCHAR(50) NOT NULL,
    ASSIGNED_DATE TIMESTAMP DEFAULT NOW() NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (FARM_ID) REFERENCES FARMS(ID) ON DELETE CASCADE
);

CREATE INDEX IDX_FARM_ASSIGNMENTS_USER_ID ON FARM_ASSIGNMENTS(USER_ID);
CREATE INDEX IDX_FARM_ASSIGNMENTS_FARM_ID ON FARM_ASSIGNMENTS(FARM_ID);
CREATE INDEX IDX_FARM_ASSIGNMENTS_ROLE ON FARM_ASSIGNMENTS(ROLE);

-- Create TASKS table
CREATE TABLE TASKS (
    ID VARCHAR(36) PRIMARY KEY,
    FARM_ID VARCHAR(36) NOT NULL,
    ASSIGNED_TO VARCHAR(36) NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(2000),
    STATUS VARCHAR(50) DEFAULT 'pending' NOT NULL,
    DUE_DATE DATE,
    PHOTO_REQUIRED CHAR(1) DEFAULT 'N',
    CREATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    CREATED_BY VARCHAR(36),
    FOREIGN KEY (FARM_ID) REFERENCES FARMS(ID) ON DELETE CASCADE,
    FOREIGN KEY (ASSIGNED_TO) REFERENCES USERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID)
);

CREATE INDEX IDX_TASKS_FARM_ID ON TASKS(FARM_ID);
CREATE INDEX IDX_TASKS_ASSIGNED_TO ON TASKS(ASSIGNED_TO);
CREATE INDEX IDX_TASKS_STATUS ON TASKS(STATUS);
CREATE INDEX IDX_TASKS_DUE_DATE ON TASKS(DUE_DATE);

-- Create ATTENDANCE table
CREATE TABLE ATTENDANCE (
    ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(36) NOT NULL,
    FARM_ID VARCHAR(36),
    CHECK_IN TIMESTAMP NOT NULL,
    CHECK_OUT TIMESTAMP,
    NOTE VARCHAR(500),
    CREATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (FARM_ID) REFERENCES FARMS(ID) ON DELETE CASCADE
);

CREATE INDEX IDX_ATTENDANCE_USER_ID ON ATTENDANCE(USER_ID);
CREATE INDEX IDX_ATTENDANCE_FARM_ID ON ATTENDANCE(FARM_ID);
CREATE INDEX IDX_ATTENDANCE_CHECK_IN ON ATTENDANCE(CHECK_IN);

-- Create EQUIPMENT_REQUESTS table
CREATE TABLE EQUIPMENT_REQUESTS (
    ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(36) NOT NULL,
    FARM_ID VARCHAR(36),
    EQUIPMENT_TYPE VARCHAR(255),
    ITEM VARCHAR(255),
    QUANTITY NUMERIC(10, 2),
    PRIORITY VARCHAR(50) DEFAULT 'medium',
    STATUS VARCHAR(50) DEFAULT 'pending',
    NOTE VARCHAR(1000),
    REQUEST_DATE TIMESTAMP DEFAULT NOW() NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (FARM_ID) REFERENCES FARMS(ID) ON DELETE CASCADE
);

CREATE INDEX IDX_EQUIPMENT_REQUESTS_USER_ID ON EQUIPMENT_REQUESTS(USER_ID);
CREATE INDEX IDX_EQUIPMENT_REQUESTS_STATUS ON EQUIPMENT_REQUESTS(STATUS);

-- Create DIAGNOSTICS table
CREATE TABLE DIAGNOSTICS (
    ID VARCHAR(36) PRIMARY KEY,
    FARM_ID VARCHAR(36) NOT NULL,
    EXPERT_ID VARCHAR(36) NOT NULL,
    PEST_RISK VARCHAR(50),
    DISEASE_RISK VARCHAR(50),
    PRESCRIPTION VARCHAR(2000),
    NOTES VARCHAR(2000),
    CREATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    FOREIGN KEY (FARM_ID) REFERENCES FARMS(ID) ON DELETE CASCADE,
    FOREIGN KEY (EXPERT_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

CREATE INDEX IDX_DIAGNOSTICS_FARM_ID ON DIAGNOSTICS(FARM_ID);
CREATE INDEX IDX_DIAGNOSTICS_EXPERT_ID ON DIAGNOSTICS(EXPERT_ID);

-- Create WEATHER table
CREATE TABLE WEATHER (
    ID VARCHAR(36) PRIMARY KEY,
    VILLAGE VARCHAR(255) NOT NULL,
    PINCODE VARCHAR(10),
    TEMPERATURE NUMERIC(5, 1),
    WEATHER_CODE INTEGER,
    DESCRIPTION VARCHAR(255),
    HUMIDITY INTEGER,
    WIND_SPEED NUMERIC(5, 1),
    RAINFALL NUMERIC(10, 2),
    LOCATION VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT NOW() NOT NULL
);

CREATE INDEX IDX_WEATHER_VILLAGE ON WEATHER(VILLAGE);
CREATE INDEX IDX_WEATHER_PINCODE ON WEATHER(PINCODE);

-- Create sample admin user (password: admin123)
INSERT INTO USERS (ID, EMAIL, PASSWORD_HASH, ROLE, NAME, CREATED_AT, UPDATED_AT)
VALUES (
    gen_random_uuid(),
    'admin@farmapp.com',
    '$2a$10$slYQmyNdGzin7olVN3p5Be7DlH.PKZbv5H8KKD0tKrxQvKt/0JZZm',
    'admin',
    'Administrator',
    NOW(),
    NOW()
)
ON CONFLICT (EMAIL) DO NOTHING;
