-- Migration V3: Add core Landowner Interface features
-- Priority: MOST IMPORTANT per requirements

-- ============================================
-- 1. LAND_DOCUMENTS - Store land ownership documents
-- ============================================
CREATE TABLE LAND_DOCUMENTS (
    ID VARCHAR(36) PRIMARY KEY,
    FARM_ID VARCHAR(36) NOT NULL,
    DOCUMENT_TYPE VARCHAR(100) NOT NULL,
    DOCUMENT_NAME VARCHAR(255) NOT NULL,
    FILE_URL VARCHAR(1000) NOT NULL,
    FILE_SIZE BIGINT,
    MIME_TYPE VARCHAR(100),
    UPLOADED_BY VARCHAR(36) NOT NULL,
    VERIFIED CHAR(1) DEFAULT 'N',
    VERIFIED_BY VARCHAR(36),
    VERIFIED_AT TIMESTAMP,
    NOTES VARCHAR(500),
    CREATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    FOREIGN KEY (FARM_ID) REFERENCES FARMS(ID) ON DELETE CASCADE,
    FOREIGN KEY (UPLOADED_BY) REFERENCES USERS(ID),
    FOREIGN KEY (VERIFIED_BY) REFERENCES USERS(ID)
);

CREATE INDEX IDX_LAND_DOCS_FARM_ID ON LAND_DOCUMENTS(FARM_ID);
CREATE INDEX IDX_LAND_DOCS_TYPE ON LAND_DOCUMENTS(DOCUMENT_TYPE);
CREATE INDEX IDX_LAND_DOCS_VERIFIED ON LAND_DOCUMENTS(VERIFIED);

COMMENT ON TABLE LAND_DOCUMENTS IS 'Stores land ownership and registration documents uploaded by landowners';
COMMENT ON COLUMN LAND_DOCUMENTS.DOCUMENT_TYPE IS 'Type: ownership_deed, tax_receipt, survey_map, lease_agreement, other';
COMMENT ON COLUMN LAND_DOCUMENTS.VERIFIED IS 'N=pending verification, Y=verified by admin';

-- ============================================
-- 2. FARM_PHOTOS - Field images and progress photos
-- ============================================
CREATE TABLE FARM_PHOTOS (
    ID VARCHAR(36) PRIMARY KEY,
    FARM_ID VARCHAR(36) NOT NULL,
    PHOTO_URL VARCHAR(1000) NOT NULL,
    PHOTO_TYPE VARCHAR(100),
    CAPTION VARCHAR(500),
    UPLOADED_BY VARCHAR(36) NOT NULL,
    UPLOADER_ROLE VARCHAR(50),
    LATITUDE NUMERIC(10, 7),
    LONGITUDE NUMERIC(10, 7),
    CREATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    FOREIGN KEY (FARM_ID) REFERENCES FARMS(ID) ON DELETE CASCADE,
    FOREIGN KEY (UPLOADED_BY) REFERENCES USERS(ID)
);

CREATE INDEX IDX_FARM_PHOTOS_FARM_ID ON FARM_PHOTOS(FARM_ID);
CREATE INDEX IDX_FARM_PHOTOS_TYPE ON FARM_PHOTOS(PHOTO_TYPE);
CREATE INDEX IDX_FARM_PHOTOS_DATE ON FARM_PHOTOS(CREATED_AT);

COMMENT ON TABLE FARM_PHOTOS IS 'Stores field photos uploaded by field managers, workers, and experts';
COMMENT ON COLUMN FARM_PHOTOS.PHOTO_TYPE IS 'Categories: crop_progress, pest_damage, disease, harvest, general, before, after';

-- ============================================
-- 3. COSTS - Expense tracking per farm
-- ============================================
CREATE TABLE COSTS (
    ID VARCHAR(36) PRIMARY KEY,
    FARM_ID VARCHAR(36) NOT NULL,
    COST_CATEGORY VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(500),
    AMOUNT NUMERIC(15, 2) NOT NULL,
    CURRENCY VARCHAR(10) DEFAULT 'INR',
    DATE_INCURRED DATE NOT NULL,
    RECEIPT_URL VARCHAR(1000),
    APPROVED CHAR(1) DEFAULT 'N',
    APPROVED_BY VARCHAR(36),
    APPROVED_AT TIMESTAMP,
    ENTERED_BY VARCHAR(36) NOT NULL,
    NOTES VARCHAR(1000),
    CREATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    FOREIGN KEY (FARM_ID) REFERENCES FARMS(ID) ON DELETE CASCADE,
    FOREIGN KEY (ENTERED_BY) REFERENCES USERS(ID),
    FOREIGN KEY (APPROVED_BY) REFERENCES USERS(ID)
);

CREATE INDEX IDX_COSTS_FARM_ID ON COSTS(FARM_ID);
CREATE INDEX IDX_COSTS_CATEGORY ON COSTS(COST_CATEGORY);
CREATE INDEX IDX_COSTS_DATE ON COSTS(DATE_INCURRED);
CREATE INDEX IDX_COSTS_APPROVED ON COSTS(APPROVED);

COMMENT ON TABLE COSTS IS 'Tracks all expenses per farm for profit calculation';
COMMENT ON COLUMN COSTS.COST_CATEGORY IS 'Categories: seeds, fertilizers, pesticides, labor, equipment, transport, other';
COMMENT ON COLUMN COSTS.APPROVED IS 'N=pending, Y=approved, R=rejected';

-- ============================================
-- 4. CROP_PLANS - Expert recommendations with landowner approval
-- ============================================
CREATE TABLE CROP_PLANS (
    ID VARCHAR(36) PRIMARY KEY,
    FARM_ID VARCHAR(36) NOT NULL,
    EXPERT_ID VARCHAR(36) NOT NULL,
    CROP_NAME VARCHAR(255) NOT NULL,
    SEASON VARCHAR(50),
    PLANTING_DATE DATE,
    EXPECTED_HARVEST_DATE DATE,
    EXPECTED_YIELD NUMERIC(12, 2),
    EXPECTED_REVENUE NUMERIC(15, 2),
    FERTILIZER_PLAN VARCHAR(2000),
    PESTICIDE_PLAN VARCHAR(2000),
    IRRIGATION_PLAN VARCHAR(2000),
    RATIONALE VARCHAR(2000),
    STATUS VARCHAR(50) DEFAULT 'pending',
    APPROVED_BY VARCHAR(36),
    APPROVED_AT TIMESTAMP,
    REJECTION_REASON VARCHAR(1000),
    CREATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    FOREIGN KEY (FARM_ID) REFERENCES FARMS(ID) ON DELETE CASCADE,
    FOREIGN KEY (EXPERT_ID) REFERENCES USERS(ID),
    FOREIGN KEY (APPROVED_BY) REFERENCES USERS(ID)
);

CREATE INDEX IDX_CROP_PLANS_FARM_ID ON CROP_PLANS(FARM_ID);
CREATE INDEX IDX_CROP_PLANS_STATUS ON CROP_PLANS(STATUS);
CREATE INDEX IDX_CROP_PLANS_EXPERT_ID ON CROP_PLANS(EXPERT_ID);

COMMENT ON TABLE CROP_PLANS IS 'Expert crop recommendations requiring landowner approval';
COMMENT ON COLUMN CROP_PLANS.STATUS IS 'pending=awaiting approval, approved=landowner approved, rejected=landowner rejected, active=currently growing, completed=harvested';
COMMENT ON COLUMN CROP_PLANS.SEASON IS 'Indian farming seasons: kharif (monsoon), rabi (winter), zaid (summer)';

-- ============================================
-- 5. HARVESTS - Yield recording and sales tracking
-- ============================================
CREATE TABLE HARVESTS (
    ID VARCHAR(36) PRIMARY KEY,
    FARM_ID VARCHAR(36) NOT NULL,
    CROP_PLAN_ID VARCHAR(36),
    CROP_NAME VARCHAR(255) NOT NULL,
    HARVEST_DATE DATE NOT NULL,
    YIELD_QUANTITY NUMERIC(12, 2) NOT NULL,
    YIELD_UNIT VARCHAR(20) DEFAULT 'kg',
    YIELD_PER_ACRE NUMERIC(12, 2),
    QUALITY_GRADE VARCHAR(50),
    SALE_PRICE NUMERIC(15, 2),
    SALE_PRICE_PER_UNIT NUMERIC(12, 2),
    BUYER_NAME VARCHAR(255),
    BUYER_TYPE VARCHAR(100),
    EXPORT_COUNTRY VARCHAR(100),
    STORAGE_LOCATION VARCHAR(500),
    TRANSPORT_COST NUMERIC(12, 2),
    TOTAL_COSTS NUMERIC(15, 2),
    REVENUE NUMERIC(15, 2),
    PROFIT NUMERIC(15, 2),
    LANDOWNER_SHARE NUMERIC(15, 2),
    GREENX_SHARE NUMERIC(15, 2),
    PAYMENT_STATUS VARCHAR(50) DEFAULT 'pending',
    PAYMENT_DATE DATE,
    RECORDED_BY VARCHAR(36) NOT NULL,
    NOTES VARCHAR(2000),
    CREATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    FOREIGN KEY (FARM_ID) REFERENCES FARMS(ID) ON DELETE CASCADE,
    FOREIGN KEY (CROP_PLAN_ID) REFERENCES CROP_PLANS(ID),
    FOREIGN KEY (RECORDED_BY) REFERENCES USERS(ID)
);

CREATE INDEX IDX_HARVESTS_FARM_ID ON HARVESTS(FARM_ID);
CREATE INDEX IDX_HARVESTS_DATE ON HARVESTS(HARVEST_DATE);
CREATE INDEX IDX_HARVESTS_CROP_PLAN ON HARVESTS(CROP_PLAN_ID);
CREATE INDEX IDX_HARVESTS_PAYMENT_STATUS ON HARVESTS(PAYMENT_STATUS);

COMMENT ON TABLE HARVESTS IS 'Records harvest yields, sales, and profit distribution (70% landowner, 30% GreenX)';
COMMENT ON COLUMN HARVESTS.BUYER_TYPE IS 'Types: local_market, mandi, contract_buyer, export, processing_unit';
COMMENT ON COLUMN HARVESTS.LANDOWNER_SHARE IS 'Calculated as 70% of profit';
COMMENT ON COLUMN HARVESTS.GREENX_SHARE IS 'Calculated as 30% of profit';

-- ============================================
-- 6. FARM_TIMELINE - Activity log and live updates
-- ============================================
CREATE TABLE FARM_TIMELINE (
    ID VARCHAR(36) PRIMARY KEY,
    FARM_ID VARCHAR(36) NOT NULL,
    EVENT_TYPE VARCHAR(100) NOT NULL,
    EVENT_TITLE VARCHAR(255) NOT NULL,
    EVENT_DESCRIPTION VARCHAR(2000),
    REFERENCE_ID VARCHAR(36),
    REFERENCE_TABLE VARCHAR(100),
    ICON VARCHAR(50),
    USER_ID VARCHAR(36),
    USER_NAME VARCHAR(255),
    USER_ROLE VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    FOREIGN KEY (FARM_ID) REFERENCES FARMS(ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

CREATE INDEX IDX_TIMELINE_FARM_ID ON FARM_TIMELINE(FARM_ID);
CREATE INDEX IDX_TIMELINE_EVENT_TYPE ON FARM_TIMELINE(EVENT_TYPE);
CREATE INDEX IDX_TIMELINE_DATE ON FARM_TIMELINE(CREATED_AT);

COMMENT ON TABLE FARM_TIMELINE IS 'Activity log showing all farm events in chronological order for transparency';
COMMENT ON COLUMN FARM_TIMELINE.EVENT_TYPE IS 'Event categories for filtering and icons';

-- ============================================
-- 7. INVENTORY - Stock management for inputs
-- ============================================
CREATE TABLE INVENTORY (
    ID VARCHAR(36) PRIMARY KEY,
    ITEM_TYPE VARCHAR(100) NOT NULL,
    ITEM_NAME VARCHAR(255) NOT NULL,
    ITEM_CODE VARCHAR(50),
    BRAND VARCHAR(255),
    UNIT VARCHAR(50),
    QUANTITY_IN_STOCK NUMERIC(12, 2) DEFAULT 0,
    REORDER_LEVEL NUMERIC(12, 2),
    UNIT_COST NUMERIC(12, 2),
    STORAGE_LOCATION VARCHAR(255),
    EXPIRY_DATE DATE,
    SUPPLIER_NAME VARCHAR(255),
    SUPPLIER_CONTACT VARCHAR(100),
    NOTES VARCHAR(1000),
    CREATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT NOW() NOT NULL
);

CREATE INDEX IDX_INVENTORY_TYPE ON INVENTORY(ITEM_TYPE);
CREATE INDEX IDX_INVENTORY_NAME ON INVENTORY(ITEM_NAME);
CREATE INDEX IDX_INVENTORY_CODE ON INVENTORY(ITEM_CODE);

COMMENT ON TABLE INVENTORY IS 'Centralized inventory management for seeds, fertilizers, pesticides, and equipment';
COMMENT ON COLUMN INVENTORY.ITEM_TYPE IS 'Categories: seed, fertilizer, pesticide, equipment';

-- ============================================
-- 8. INVENTORY_TRANSACTIONS - Track usage and restocking
-- ============================================
CREATE TABLE INVENTORY_TRANSACTIONS (
    ID VARCHAR(36) PRIMARY KEY,
    INVENTORY_ID VARCHAR(36) NOT NULL,
    FARM_ID VARCHAR(36),
    TRANSACTION_TYPE VARCHAR(20) NOT NULL,
    QUANTITY NUMERIC(12, 2) NOT NULL,
    UNIT VARCHAR(50),
    COST_TOTAL NUMERIC(12, 2),
    TRANSACTION_DATE TIMESTAMP DEFAULT NOW() NOT NULL,
    PERFORMED_BY VARCHAR(36) NOT NULL,
    PURPOSE VARCHAR(500),
    REFERENCE_TASK_ID VARCHAR(36),
    NOTES VARCHAR(1000),
    CREATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    FOREIGN KEY (INVENTORY_ID) REFERENCES INVENTORY(ID) ON DELETE CASCADE,
    FOREIGN KEY (FARM_ID) REFERENCES FARMS(ID),
    FOREIGN KEY (PERFORMED_BY) REFERENCES USERS(ID),
    FOREIGN KEY (REFERENCE_TASK_ID) REFERENCES TASKS(ID)
);

CREATE INDEX IDX_INV_TRANS_INVENTORY ON INVENTORY_TRANSACTIONS(INVENTORY_ID);
CREATE INDEX IDX_INV_TRANS_FARM ON INVENTORY_TRANSACTIONS(FARM_ID);
CREATE INDEX IDX_INV_TRANS_DATE ON INVENTORY_TRANSACTIONS(TRANSACTION_DATE);
CREATE INDEX IDX_INV_TRANS_TYPE ON INVENTORY_TRANSACTIONS(TRANSACTION_TYPE);

COMMENT ON TABLE INVENTORY_TRANSACTIONS IS 'Tracks all inventory movements (restocking and usage)';
COMMENT ON COLUMN INVENTORY_TRANSACTIONS.TRANSACTION_TYPE IS 'in=purchase/restock, out=usage on farm';

-- ============================================
-- 9. LAB_SAMPLES - Sample tracking for diagnostic lab
-- ============================================
CREATE TABLE LAB_SAMPLES (
    ID VARCHAR(36) PRIMARY KEY,
    SAMPLE_CODE VARCHAR(50) UNIQUE NOT NULL,
    FARM_ID VARCHAR(36) NOT NULL,
    SAMPLE_TYPE VARCHAR(100) NOT NULL,
    COLLECTION_DATE DATE NOT NULL,
    COLLECTED_BY VARCHAR(36) NOT NULL,
    SUBMITTED_DATE DATE,
    LOCATION_DESCRIPTION VARCHAR(500),
    TEST_REQUESTED VARCHAR(500),
    PRIORITY VARCHAR(50) DEFAULT 'normal',
    STATUS VARCHAR(50) DEFAULT 'collected',
    ASSIGNED_TECHNICIAN VARCHAR(255),
    EXPECTED_COMPLETION_DATE DATE,
    ACTUAL_COMPLETION_DATE DATE,
    NOTES VARCHAR(2000),
    CREATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    FOREIGN KEY (FARM_ID) REFERENCES FARMS(ID) ON DELETE CASCADE,
    FOREIGN KEY (COLLECTED_BY) REFERENCES USERS(ID)
);

CREATE INDEX IDX_LAB_SAMPLES_FARM_ID ON LAB_SAMPLES(FARM_ID);
CREATE INDEX IDX_LAB_SAMPLES_CODE ON LAB_SAMPLES(SAMPLE_CODE);
CREATE INDEX IDX_LAB_SAMPLES_STATUS ON LAB_SAMPLES(STATUS);
CREATE INDEX IDX_LAB_SAMPLES_TYPE ON LAB_SAMPLES(SAMPLE_TYPE);

COMMENT ON TABLE LAB_SAMPLES IS 'Tracks all lab samples from collection to report completion';
COMMENT ON COLUMN LAB_SAMPLES.SAMPLE_TYPE IS 'Types: soil, plant_tissue, water, pest, disease';
COMMENT ON COLUMN LAB_SAMPLES.STATUS IS 'Workflow: collected → submitted → in_progress → completed → reported';

-- ============================================
-- 10. LAB_REPORTS - Test results and recommendations
-- ============================================
CREATE TABLE LAB_REPORTS (
    ID VARCHAR(36) PRIMARY KEY,
    SAMPLE_ID VARCHAR(36) NOT NULL,
    FARM_ID VARCHAR(36) NOT NULL,
    REPORT_DATE DATE NOT NULL,
    TEST_RESULTS TEXT,
    NPK_NITROGEN NUMERIC(10, 2),
    NPK_PHOSPHORUS NUMERIC(10, 2),
    NPK_POTASSIUM NUMERIC(10, 2),
    SOIL_PH NUMERIC(4, 2),
    ORGANIC_CARBON NUMERIC(10, 2),
    SOIL_TEXTURE VARCHAR(100),
    PATHOGEN_DETECTED VARCHAR(500),
    DISEASE_NAME VARCHAR(255),
    SEVERITY VARCHAR(50),
    RECOMMENDATIONS TEXT,
    FERTILIZER_PRESCRIPTION VARCHAR(2000),
    TREATMENT_PRESCRIPTION VARCHAR(2000),
    GENERATED_BY VARCHAR(255),
    REVIEWED_BY VARCHAR(36),
    REPORT_URL VARCHAR(1000),
    CREATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    FOREIGN KEY (SAMPLE_ID) REFERENCES LAB_SAMPLES(ID) ON DELETE CASCADE,
    FOREIGN KEY (FARM_ID) REFERENCES FARMS(ID) ON DELETE CASCADE,
    FOREIGN KEY (REVIEWED_BY) REFERENCES USERS(ID)
);

CREATE INDEX IDX_LAB_REPORTS_SAMPLE_ID ON LAB_REPORTS(SAMPLE_ID);
CREATE INDEX IDX_LAB_REPORTS_FARM_ID ON LAB_REPORTS(FARM_ID);
CREATE INDEX IDX_LAB_REPORTS_DATE ON LAB_REPORTS(REPORT_DATE);

COMMENT ON TABLE LAB_REPORTS IS 'Stores lab test results, diagnoses, and prescriptions';
COMMENT ON COLUMN LAB_REPORTS.TEST_RESULTS IS 'Complete test results in JSON or structured format';
