-- Migration V7: Add AI conversation, insights, recommendations, and analysis tables
-- These tables support the generative AI system (GPT-4 + rule-based fallback)

-- ============================================
-- 1. AI_CONVERSATIONS - Multi-turn chat history
-- ============================================
CREATE TABLE IF NOT EXISTS AI_CONVERSATIONS (
    ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(36),
    FARM_ID VARCHAR(36),
    SESSION_ID VARCHAR(36),
    ROLE VARCHAR(20) NOT NULL DEFAULT 'USER',
    CONTENT TEXT,
    TYPE VARCHAR(30) DEFAULT 'CHAT',
    MODEL_USED VARCHAR(50) DEFAULT 'rule-based',
    CONFIDENCE_SCORE INTEGER,
    ACTED_UPON BOOLEAN DEFAULT FALSE,
    FEEDBACK_RATING INTEGER,
    METADATA TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS IDX_AI_CONV_SESSION ON AI_CONVERSATIONS(SESSION_ID);
CREATE INDEX IF NOT EXISTS IDX_AI_CONV_USER ON AI_CONVERSATIONS(USER_ID);
CREATE INDEX IF NOT EXISTS IDX_AI_CONV_FARM ON AI_CONVERSATIONS(FARM_ID);
CREATE INDEX IF NOT EXISTS IDX_AI_CONV_TYPE ON AI_CONVERSATIONS(TYPE);

-- ============================================
-- 2. AI_INSIGHTS - Autonomous AI-generated insights
-- ============================================
CREATE TABLE IF NOT EXISTS AI_INSIGHTS (
    ID VARCHAR(36) PRIMARY KEY,
    FARM_ID VARCHAR(36),
    USER_ID VARCHAR(36),
    CATEGORY VARCHAR(50),
    SEVERITY VARCHAR(20) DEFAULT 'INFO',
    TITLE VARCHAR(255),
    SUMMARY VARCHAR(500),
    DETAILS TEXT,
    SUGGESTED_ACTIONS TEXT,
    CONFIDENCE_SCORE INTEGER DEFAULT 75,
    IS_READ BOOLEAN DEFAULT FALSE,
    IS_DISMISSED BOOLEAN DEFAULT FALSE,
    EXPIRES_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS IDX_AI_INSIGHTS_FARM ON AI_INSIGHTS(FARM_ID);
CREATE INDEX IF NOT EXISTS IDX_AI_INSIGHTS_USER ON AI_INSIGHTS(USER_ID);
CREATE INDEX IF NOT EXISTS IDX_AI_INSIGHTS_SEVERITY ON AI_INSIGHTS(SEVERITY);
CREATE INDEX IF NOT EXISTS IDX_AI_INSIGHTS_DISMISSED ON AI_INSIGHTS(IS_DISMISSED);

-- ============================================
-- 3. AI_RECOMMENDATIONS - Stored AI recommendations
-- ============================================
CREATE TABLE IF NOT EXISTS AI_RECOMMENDATIONS (
    ID VARCHAR(36) PRIMARY KEY,
    FARM_ID VARCHAR(36),
    USER_ID VARCHAR(36),
    CONVERSATION_ID VARCHAR(36),
    TYPE VARCHAR(50),
    TITLE VARCHAR(255),
    DESCRIPTION TEXT,
    PRIORITY VARCHAR(20) DEFAULT 'NORMAL',
    STATUS VARCHAR(20) DEFAULT 'PENDING',
    CONFIDENCE_SCORE INTEGER DEFAULT 75,
    RELATED_CROP VARCHAR(100),
    VALID_UNTIL TIMESTAMP,
    ACCEPTED_AT TIMESTAMP,
    REJECTED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS IDX_AI_RECS_FARM ON AI_RECOMMENDATIONS(FARM_ID);
CREATE INDEX IF NOT EXISTS IDX_AI_RECS_STATUS ON AI_RECOMMENDATIONS(STATUS);
CREATE INDEX IF NOT EXISTS IDX_AI_RECS_TYPE ON AI_RECOMMENDATIONS(TYPE);

-- ============================================
-- 4. AI_ANALYSIS_RESULTS - Stored analysis snapshots
-- ============================================
CREATE TABLE IF NOT EXISTS AI_ANALYSIS_RESULTS (
    ID VARCHAR(36) PRIMARY KEY,
    FARM_ID VARCHAR(36),
    USER_ID VARCHAR(36),
    ANALYSIS_TYPE VARCHAR(50),
    OVERALL_SCORE INTEGER,
    RISK_LEVEL VARCHAR(20),
    SOIL_SCORE INTEGER,
    NUTRIENT_SCORE INTEGER,
    MOISTURE_SCORE INTEGER,
    DISEASE_SCORE INTEGER,
    ALERT_COUNT INTEGER DEFAULT 0,
    RECOMMENDATION_COUNT INTEGER DEFAULT 0,
    MODEL_USED VARCHAR(50) DEFAULT 'rule-based',
    RAW_INPUT TEXT,
    RAW_OUTPUT TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS IDX_AI_ANALYSIS_FARM ON AI_ANALYSIS_RESULTS(FARM_ID);
CREATE INDEX IF NOT EXISTS IDX_AI_ANALYSIS_TYPE ON AI_ANALYSIS_RESULTS(ANALYSIS_TYPE);
CREATE INDEX IF NOT EXISTS IDX_AI_ANALYSIS_DATE ON AI_ANALYSIS_RESULTS(CREATED_AT);
