-- Migration V8: Add farm workflow tables for complete onboarding and management
-- Supports: farm status tracking, soil reports, crop suggestions, schedule,
--           field updates, notifications, and site visit reports

-- ============================================
-- 1. Add STATUS column to FARMS table
-- ============================================
ALTER TABLE FARMS ADD COLUMN IF NOT EXISTS STATUS VARCHAR(50) DEFAULT 'Pending Review';

-- Backfill existing rows that have no status yet
UPDATE FARMS SET STATUS = 'Pending Review' WHERE STATUS IS NULL;

CREATE INDEX IF NOT EXISTS IDX_FARMS_STATUS ON FARMS(STATUS);

COMMENT ON COLUMN FARMS.STATUS IS 'Workflow status: Pending Review, Assigned, Site Visited, Soil Tested, Crop Suggested, Schedule Created, In Progress';

-- ============================================
-- 2. SOIL_REPORTS - Soil testing results from Expert
-- ============================================
CREATE TABLE IF NOT EXISTS SOIL_REPORTS (
    ID VARCHAR(36) PRIMARY KEY,
    FARM_ID VARCHAR(36) NOT NULL,
    EXPERT_ID VARCHAR(36) NOT NULL,
    PH NUMERIC(4, 2),
    NITROGEN NUMERIC(10, 2),
    PHOSPHORUS NUMERIC(10, 2),
    POTASSIUM NUMERIC(10, 2),
    ORGANIC_MATTER NUMERIC(10, 2),
    MOISTURE NUMERIC(5, 2),
    TEXTURE VARCHAR(100),
    NOTES VARCHAR(2000),
    SUBMITTED_DATE TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (FARM_ID) REFERENCES FARMS(ID) ON DELETE CASCADE,
    FOREIGN KEY (EXPERT_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_SOIL_REPORTS_FARM_ID ON SOIL_REPORTS(FARM_ID);
CREATE INDEX IF NOT EXISTS IDX_SOIL_REPORTS_EXPERT_ID ON SOIL_REPORTS(EXPERT_ID);
CREATE INDEX IF NOT EXISTS IDX_SOIL_REPORTS_SUBMITTED_DATE ON SOIL_REPORTS(SUBMITTED_DATE);
CREATE INDEX IF NOT EXISTS IDX_SOIL_REPORTS_CREATED_AT ON SOIL_REPORTS(CREATED_AT);

COMMENT ON TABLE SOIL_REPORTS IS 'Soil testing results submitted by Expert after lab analysis';
COMMENT ON COLUMN SOIL_REPORTS.TEXTURE IS 'Soil texture classification: loamy, sandy, clay, silt, etc.';

-- ============================================
-- 3. CROP_SUGGESTIONS - Crop recommendations from Expert
-- ============================================
CREATE TABLE IF NOT EXISTS CROP_SUGGESTIONS (
    ID VARCHAR(36) PRIMARY KEY,
    FARM_ID VARCHAR(36) NOT NULL,
    EXPERT_ID VARCHAR(36) NOT NULL,
    CROP_NAME VARCHAR(255) NOT NULL,
    VARIETY VARCHAR(255),
    EXPECTED_YIELD NUMERIC(10, 2),
    EXPECTED_REVENUE NUMERIC(15, 2),
    SOWING_DATE DATE,
    HARVEST_DATE DATE,
    REASONING VARCHAR(2000),
    NOTES VARCHAR(2000),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (FARM_ID) REFERENCES FARMS(ID) ON DELETE CASCADE,
    FOREIGN KEY (EXPERT_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_CROP_SUGGESTIONS_FARM_ID ON CROP_SUGGESTIONS(FARM_ID);
CREATE INDEX IF NOT EXISTS IDX_CROP_SUGGESTIONS_EXPERT_ID ON CROP_SUGGESTIONS(EXPERT_ID);
CREATE INDEX IF NOT EXISTS IDX_CROP_SUGGESTIONS_CREATED_AT ON CROP_SUGGESTIONS(CREATED_AT);

COMMENT ON TABLE CROP_SUGGESTIONS IS 'Crop recommendations submitted by Expert based on soil test results and farm conditions';
COMMENT ON COLUMN CROP_SUGGESTIONS.REASONING IS 'Expert justification for recommending this crop';

-- ============================================
-- 4. SCHEDULE_ITEMS - Farming operations calendar
-- ============================================
CREATE TABLE IF NOT EXISTS SCHEDULE_ITEMS (
    ID VARCHAR(36) PRIMARY KEY,
    FARM_ID VARCHAR(36) NOT NULL,
    EXPERT_ID VARCHAR(36) NOT NULL,
    OPERATION_NAME VARCHAR(255) NOT NULL,
    SCHEDULED_DATE DATE NOT NULL,
    SCHEDULED_END_DATE DATE,
    DESCRIPTION VARCHAR(2000),
    NOTES VARCHAR(2000),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (FARM_ID) REFERENCES FARMS(ID) ON DELETE CASCADE,
    FOREIGN KEY (EXPERT_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_SCHEDULE_ITEMS_FARM_ID ON SCHEDULE_ITEMS(FARM_ID);
CREATE INDEX IF NOT EXISTS IDX_SCHEDULE_ITEMS_EXPERT_ID ON SCHEDULE_ITEMS(EXPERT_ID);
CREATE INDEX IF NOT EXISTS IDX_SCHEDULE_ITEMS_SCHEDULED_DATE ON SCHEDULE_ITEMS(SCHEDULED_DATE);
CREATE INDEX IF NOT EXISTS IDX_SCHEDULE_ITEMS_CREATED_AT ON SCHEDULE_ITEMS(CREATED_AT);

COMMENT ON TABLE SCHEDULE_ITEMS IS 'Farming operations calendar created by Expert (e.g. Soil Preparation, Sowing, Irrigation, Pest Control, Harvesting)';
COMMENT ON COLUMN SCHEDULE_ITEMS.SCHEDULED_END_DATE IS 'Optional end date for multi-day operations';

-- ============================================
-- 5. FIELD_UPDATES - Ongoing field progress updates from Field Manager
-- ============================================
CREATE TABLE IF NOT EXISTS FIELD_UPDATES (
    ID VARCHAR(36) PRIMARY KEY,
    FARM_ID VARCHAR(36) NOT NULL,
    FIELD_MANAGER_ID VARCHAR(36) NOT NULL,
    UPDATE_TYPE VARCHAR(50) NOT NULL,
    TITLE VARCHAR(255),
    DESCRIPTION VARCHAR(2000),
    PHOTO_URL VARCHAR(500),
    AMOUNT NUMERIC(15, 2),
    TRANSACTION_TYPE VARCHAR(50),
    RELATED_SCHEDULE_ITEM_ID VARCHAR(36),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (FARM_ID) REFERENCES FARMS(ID) ON DELETE CASCADE,
    FOREIGN KEY (FIELD_MANAGER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (RELATED_SCHEDULE_ITEM_ID) REFERENCES SCHEDULE_ITEMS(ID) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS IDX_FIELD_UPDATES_FARM_ID ON FIELD_UPDATES(FARM_ID);
CREATE INDEX IF NOT EXISTS IDX_FIELD_UPDATES_FIELD_MANAGER_ID ON FIELD_UPDATES(FIELD_MANAGER_ID);
CREATE INDEX IF NOT EXISTS IDX_FIELD_UPDATES_UPDATE_TYPE ON FIELD_UPDATES(UPDATE_TYPE);
CREATE INDEX IF NOT EXISTS IDX_FIELD_UPDATES_CREATED_AT ON FIELD_UPDATES(CREATED_AT);
CREATE INDEX IF NOT EXISTS IDX_FIELD_UPDATES_SCHEDULE_ITEM ON FIELD_UPDATES(RELATED_SCHEDULE_ITEM_ID);

COMMENT ON TABLE FIELD_UPDATES IS 'Ongoing field progress updates submitted by Field Manager (photos, notes, expenses, income)';
COMMENT ON COLUMN FIELD_UPDATES.UPDATE_TYPE IS 'Type of update: photo, note, expense, income';
COMMENT ON COLUMN FIELD_UPDATES.TRANSACTION_TYPE IS 'For financial updates: expense or income';
COMMENT ON COLUMN FIELD_UPDATES.PHOTO_URL IS 'URL of uploaded photo (only for photo update type)';
COMMENT ON COLUMN FIELD_UPDATES.AMOUNT IS 'Monetary amount (only for expense/income update types)';

-- ============================================
-- 6. NOTIFICATIONS - System-wide notification store
-- ============================================
CREATE TABLE IF NOT EXISTS NOTIFICATIONS (
    ID VARCHAR(36) PRIMARY KEY,
    RECIPIENT_ID VARCHAR(36) NOT NULL,
    SENDER_ID VARCHAR(36),
    FARM_ID VARCHAR(36),
    NOTIFICATION_TYPE VARCHAR(100) NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    MESSAGE VARCHAR(2000),
    IS_READ CHAR(1) DEFAULT 'N' NOT NULL,
    ACTION_URL VARCHAR(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    READ_AT TIMESTAMP,
    FOREIGN KEY (RECIPIENT_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (SENDER_ID) REFERENCES USERS(ID) ON DELETE SET NULL,
    FOREIGN KEY (FARM_ID) REFERENCES FARMS(ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_NOTIFICATIONS_RECIPIENT_ID ON NOTIFICATIONS(RECIPIENT_ID);
CREATE INDEX IF NOT EXISTS IDX_NOTIFICATIONS_SENDER_ID ON NOTIFICATIONS(SENDER_ID);
CREATE INDEX IF NOT EXISTS IDX_NOTIFICATIONS_FARM_ID ON NOTIFICATIONS(FARM_ID);
CREATE INDEX IF NOT EXISTS IDX_NOTIFICATIONS_IS_READ ON NOTIFICATIONS(IS_READ);
CREATE INDEX IF NOT EXISTS IDX_NOTIFICATIONS_NOTIFICATION_TYPE ON NOTIFICATIONS(NOTIFICATION_TYPE);
CREATE INDEX IF NOT EXISTS IDX_NOTIFICATIONS_CREATED_AT ON NOTIFICATIONS(CREATED_AT);

COMMENT ON TABLE NOTIFICATIONS IS 'System-wide notifications for all workflow events';
COMMENT ON COLUMN NOTIFICATIONS.NOTIFICATION_TYPE IS 'Event type: farm_registered, farm_assigned, sample_collected, soil_report_ready, crop_suggested, schedule_created, field_update';
COMMENT ON COLUMN NOTIFICATIONS.IS_READ IS 'N=unread, Y=read';
COMMENT ON COLUMN NOTIFICATIONS.ACTION_URL IS 'Optional deep-link to the relevant page in the frontend';

-- ============================================
-- 7. SITE_VISIT_REPORTS - Site visit reports from Field Manager
-- ============================================
CREATE TABLE IF NOT EXISTS SITE_VISIT_REPORTS (
    ID VARCHAR(36) PRIMARY KEY,
    FARM_ID VARCHAR(36) NOT NULL,
    FIELD_MANAGER_ID VARCHAR(36) NOT NULL,
    VISIT_DATE DATE NOT NULL,
    OBSERVATIONS VARCHAR(2000),
    SOIL_SAMPLE_COLLECTED CHAR(1) DEFAULT 'Y' NOT NULL,
    PHOTO_URL VARCHAR(500),
    NOTES VARCHAR(2000),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (FARM_ID) REFERENCES FARMS(ID) ON DELETE CASCADE,
    FOREIGN KEY (FIELD_MANAGER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_SITE_VISIT_REPORTS_FARM_ID ON SITE_VISIT_REPORTS(FARM_ID);
CREATE INDEX IF NOT EXISTS IDX_SITE_VISIT_REPORTS_FIELD_MANAGER_ID ON SITE_VISIT_REPORTS(FIELD_MANAGER_ID);
CREATE INDEX IF NOT EXISTS IDX_SITE_VISIT_REPORTS_VISIT_DATE ON SITE_VISIT_REPORTS(VISIT_DATE);
CREATE INDEX IF NOT EXISTS IDX_SITE_VISIT_REPORTS_CREATED_AT ON SITE_VISIT_REPORTS(CREATED_AT);

COMMENT ON TABLE SITE_VISIT_REPORTS IS 'Site visit reports submitted by Field Manager after visiting the farm';
COMMENT ON COLUMN SITE_VISIT_REPORTS.SOIL_SAMPLE_COLLECTED IS 'Y=soil sample collected during visit, N=not collected';
